### ISSUE TITLE
Spectral Count keeps rejecting protein database

### ISSUE THREAD

**Issue by afikolami** [crux-toolkit/crux-toolkit#638]
Greetings. I keep getting an error message 'Protein doesn't have the full sequence' when using spectral count. My PSM file data input (named 'score') is in the format of Crux tab delimited, but the data was obtained from PEAKS software.
[spectral-counts.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10896400/spectral-counts.log.txt)
[score.txt](https://github.com/crux-toolkit/crux-toolkit/files/10896404/score.txt)
[Belangkas2.fasta.txt](https://github.com/crux-toolkit/crux-toolkit/files/10896426/Belangkas2.fasta.txt)

**Comment by wsnoble** [comment]
The error message is misleading, but it looks to me like your input file (scores.txt) does not contain anything at all in the proteinIds column. This makes it impossible for the program to map the counts to proteins.

**Comment by wsnoble** [comment]
We should fix it so that the program notices that the protein ID field is empty and gives an informative error message, rather than trying to search for an empty protein ID in the FASTA file.

Also, it looks like the program is not handling DOS EOLs properly: the empty protein field had a ^M in it.

**Comment by bmx8177** [comment]
Hello - how did you generate the scores.txt file? If you generated it using Percolator then this is likely related to issue #629. This is the issue that I am going to debug next.

**Comment by afikolami** [comment]
Hello. Thanks for the prompt reply. I actually generated my data through PEAKS Studio. I just copied the results of their scores and q-values into the Crux tab format. I will try the spectral count program again after I copied the protein Ids into the column. For that I have another question.

How do do I write peptides that map to multiple protein Ids in my input file? Can I get some examples as the tutorial results does not have any.

**Comment by afikolami** [comment]
Hello. I've inserted the protein Ids into my input file and I ran the spectral-counts. Now I'm still getting the 'Protein doesn't have the full sequence' error message, but this time the program gave out a protein Id.
[score2.txt](https://github.com/crux-toolkit/crux-toolkit/files/10907065/score2.txt)
[spectral-counts.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10907116/spectral-counts.log.txt)
[spectral-counts.target.txt](https://github.com/crux-toolkit/crux-toolkit/files/10907118/spectral-counts.target.txt)

**Comment by wsnoble** [comment]
Which protein is it failing to find? Did you verify that that protein occurs in your FASTA file?

**Comment by afikolami** [comment]
The log file only shows one protein id that's failed to find (Q9U8Z4). But the target result file shows multiple proteins with '-nan(ind)' at the NSAF score column. I've verified that all of those proteins are indeed occurs in my FASTA file and their sequences are correct from the UniProt database.

**Comment by wsnoble** [comment]
The problem seems to be related to the DOS end-of-line characters on Windows.  The error message has a ^M character embedded into the protein ID:

`Protein Q9U8Z4^M doesn't have the full sequence`

I am testing on a Linux box, so I converted the input file to Linux EOLs, and now the command runs to completion.  I do get some warnings about peptides that are missing from the database:

```
crux spectral-counts --overwrite T --threshold 0.99 --protein-database Belangkas2.fasta score2.txt
INFO: Writing results to output directory 'crux-output'.
INFO: CPU: pyrrolysine.gs.washington.edu
INFO: Crux version: 4.1-f575777e-2023-01-13
INFO: Wed Mar  8 09:56:48 PST 2023
INFO: Beginning spectral-counts.
INFO: Total proteins found: 663
ERROR: could not find IFLSPKYDELGNEIK in protein A1X1V3
MTVKEKQSRLLPLFKHLTSLTRDQPPVSQRDDRLKDVGHLPRGTLFSLFHSKHLEEATHLYEILYGAKDFDDLIHLLEQARDTVNEGMFVYAATVAVLHRDDCRGVTVPPIEEVFPDRFIPAETIRHADKEVTAHPDKDIVVEFEETGNILDPEYRLAYYREDVSINRHHWHWHIVYPATWRPEVMHKEKDRKGELFYYMHQQMCARYDCERLSNGMHRMYPFNNFHEDLEGYSPHLTSLISGLNYGTRPDGLKLHDLHDVTIQDRERWRERIHNAIDLKMVHDHDGKEIAIHEENGIDILGALVESSYESVNQGFYGSLHNWGHVLTARAHDPEGKFYENPGVMSDTSTSLRDPIFYRWHRTLDNLFQEYKESLSPYTKEELSFPGIEVLSASVKTKTNNVITTSMVESELELSHGINFGTDHSVKVKYHHPDHEPFSYHINVSNNSGSPKHATVRIFLAPKYDELGNLLHPNEQRRFCIELDKFHKELNAGKTEITRNSVDSSVTISTLRTFNELNDGVGVSENADEYCSCGWPKNMLIPRGNHKGMVFELFVMLTDWEHDNVSGKGQESPMCDDAVSYCGAKDSKYPDKKHMGFPFDRRIDAPDIEEFLTPNMTLTDIKIKFEGKKPK
ERROR: could not find ESLSPYTKEELSFPGIEVLSASVK in protein A1X1V2
MTLHDNQVRVCHLFEQLSSATVTGNGEKHKHSDRLKNVSKLQPGAIFSCFHPEHLEEARHLYEVFWEAGDFDDFIEVAKEARTFVNEGLFAFACEVAVLHRDDCKGLHVPPVQEIFPDKFIPSIAINEAFKKAHIRPEFDESPILVDVHDTGNILDPEYRLAYYREDVGINAHHWHWHLVYPSTWDPKYFSKKKDRKGELFYYMHQQMCARYDCERLSNGMHRMLPFHNFDEPLAGYAPHLSHIASGKYYSPRPDGLSLRDLGDIAISDMVRMRERISDSIHLGYVIDSEGNHKNLDEHHGIDILGALVESSHESVNKEYYGNLHNWGHVTMARIHDPDGRFHEEPGVMSDTSTSLRDPLFYNWHGFIDDLFQEYKNTLKPYDHGMLNFTDIQIQNVTLHARVDNVIHTFMRENELELKYGVNLGHARSVKARYYHLDHEPFSYAVDVQNNSASDKHATVRIFLSPKYDELGNEIKANDLRHTAIELDKFKTDLHPGKNTVVRHSLDSSVTLSHQPTFEDLLHGIGLNDNKSEFCSCGWPSHPLVPKGNVKGMEFHLFVMLTDWDKDKVDGSESVACVDAVSYCGARDHKYPDMKPMGFLFDRPILTEHISDFLTNNMFIKDIHIKFHE
ERROR: could not find FHENPGVMSDTSTSLRDPIFYR in protein A1X1V3
MTVKEKQSRLLPLFKHLTSLTRDQPPVSQRDDRLKDVGHLPRGTLFSLFHSKHLEEATHLYEILYGAKDFDDLIHLLEQARDTVNEGMFVYAATVAVLHRDDCRGVTVPPIEEVFPDRFIPAETIRHADKEVTAHPDKDIVVEFEETGNILDPEYRLAYYREDVSINRHHWHWHIVYPATWRPEVMHKEKDRKGELFYYMHQQMCARYDCERLSNGMHRMYPFNNFHEDLEGYSPHLTSLISGLNYGTRPDGLKLHDLHDVTIQDRERWRERIHNAIDLKMVHDHDGKEIAIHEENGIDILGALVESSYESVNQGFYGSLHNWGHVLTARAHDPEGKFYENPGVMSDTSTSLRDPIFYRWHRTLDNLFQEYKESLSPYTKEELSFPGIEVLSASVKTKTNNVITTSMVESELELSHGINFGTDHSVKVKYHHPDHEPFSYHINVSNNSGSPKHATVRIFLAPKYDELGNLLHPNEQRRFCIELDKFHKELNAGKTEITRNSVDSSVTISTLRTFNELNDGVGVSENADEYCSCGWPKNMLIPRGNHKGMVFELFVMLTDWEHDNVSGKGQESPMCDDAVSYCGAKDSKYPDKKHMGFPFDRRIDAPDIEEFLTPNMTLTDIKIKFEGKKPK
INFO: Assigning index 0 to score2.txt.
INFO: Number of matches:215
INFO: Number of matches passed the threshold 215
INFO: Number of peptides 119
INFO: Number of proteins 24
INFO: Elapsed time: 0.0348 s
INFO: Finished crux spectral-counts.
INFO: Return Code:0
```

I noticed that the peptide that it can't find (IFLSPKYDELGNEIK in protein A1X1V3) actually does occur in protein A1X1V2, which suggests that perhaps the protein IDs in your input file are somehow mismatched.

Meanwhile, we will work on fixing the ^M problem on Windows.

[spectral-counts.target.txt](https://github.com/crux-toolkit/crux-toolkit/files/10923512/spectral-counts.target.txt)

**Comment by kfattila** [comment]
Is this still an open issue? @bmx8177 @wsnoble

**Comment by wsnoble** [comment]
I am not sure because I don't have a windows system to test it on.  Here is the command line that worked ok on a linux box:

`crux spectral-counts --overwrite T --threshold 0.99 --protein-database Belangkas2.fasta score2.txt`

@kfattila, can you test it?  The input files are linked above.

**Comment by kfattila** [comment]
It hangs, and don't finish, and don't use any CPU:

```
d:\crux-stable>src\Release\crux.exe spectral-counts --overwrite T --threshold 0.99 --protein-database spectral-counts-test\Belangkas2.fasta spectral-counts-test\score2.txt
INFO: Writing results to output directory 'crux-output'.
INFO: CPU: AIC2
INFO: Crux version: 4.2-6031fb2a-2024-11-08
INFO: Wed 11/13/2024
INFO: Beginning spectral-counts.
```
